### ISSUE TITLE
Token validation error - The Signature key was not found

### ISSUE THREAD

**Issue by gituser22kk** [okta/okta-aspnet#153]
Hello,
We use .NET Core 2.2 (sdk version 1.3.0). We suddenly started to get the following error when the protected APIs are hit with valid tokens. The Tokens are created fine, aren't expired and have valid claims, issuer, audience etc. 
Error in the response header:
www-Authenticate Bearer error "Invalid_token", error_description = "The Signature key was not found".

We verified our startup and the default schemes are correctly setup as `ApiAuthenticationScheme` and the `OktaDomain `and `Audience `is also correctly setup using ` .AddOktaWebApi`

We use the default authorization server with the automatic key rotation. What can cause this error? Any suggestions?

Thank you!

**Comment by bryanapellanes-okta** [comment]
@gituser22kk,
Thanks for reaching out, and sorry for the inconvenience.  I will inquire internally to get additional information about the error and its potential causes.  In the mean time are you able to provide code that reproduces the issue, preferably in a temporary repository that I can clone and run?  This will help greatly to determine the root cause of the issue.

Thanks!

**Comment by bryanapellanes-okta** [comment]
@gituser22kk,
As something to try, are you setting the authParameters?  See this devforum help article for more: [https://devforum.okta.com/t/error-the-signature-key-was-not-found/696/2](https://devforum.okta.com/t/error-the-signature-key-was-not-found/696/2).

**Comment by gituser22kk** [comment]
Thank you for your help. There was a settings issue in configuration file. Sorry for any inconvenience. This can be closed.
