### ISSUE TITLE
Sign out redirects to a url that returns error about missing client_id

### ISSUE THREAD

**Issue by liiri** [okta/okta-aspnet#155]
I'm using `Okta.AspNetCore` version `3.2.0` on .NET Core 3.1

This is my authentication controller:

```
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Mvc;

namespace MyApp
{
    public abstract class BaseAuthenticationController : Controller
    {
        public IActionResult SignIn(string returnUrl)
            => Challenge(
                new AuthenticationProperties
                {
                    RedirectUri = "/",
                    IsPersistent = true
                },
                OpenIdConnectDefaults.AuthenticationScheme
            );

        public async Task<IActionResult> SignOutAsync()
        {
            await HttpContext.SignOutAsync();
            return SignOut(
                    new AuthenticationProperties(),
                    OpenIdConnectDefaults.AuthenticationScheme,
                    CookieAuthenticationDefaults.AuthenticationScheme
                );
        }
    }
}
```

When session expires, my client calls this sign-out method. However, maybe due to session expiring, I'm getting redirected to `https://DOMAIN.okta.com/...` that returns an error:

![image](https://user-images.githubusercontent.com/53004117/99426214-81dca700-290c-11eb-8772-85bd52383b67.png)

The same flow works if I manually log-out while session still haven't expired.

Reproduced across multiple OS and browsers.

**Comment by laura-rodriguez** [comment]
Hi @liiri ,

Sorry for the inconvenience.

Can you please share a fiddler log when the logout request is being made? We usually send the `id_token` as a logout query param, and it's possible that the id_token value is null since the session expired. I want to verify what the logout request looks like.

Thanks!

**Comment by liiri** [comment]
Hi @laura-rodriguez thanks for the quick reply :)
Can't get a proper Fiddler or similar at the moment, but can detail from browser feed.
Also looking at it more carefully, I find my initial claim was not accurate.

Step 1 - web client get error due to session expired when doing some api call
```
GET
https://localhost:5001/api/XXX
Status Code: 302 Redirect
```
Response header includes proper redirect url (actual ids were obfuscated or censored):
```
https://DOMAIN.okta.com/oauth2/v1/authorize?client_id=e06oahP0aQWr0xr4Sn4x&redirect_uri=https%3A%2F%2Flocalhost%3A5001%2Fauthorization-code%2Fcallback&response_type=code&scope=openid%20profile%20email%20groups&code_challenge=xxx&code_challenge_method=S256&response_mode=form_post&nonce=xxx&state=xxx&x-client-ver=5.5.0.0
```

Step 2 - At this point you might argue my client should follow the redirect and it does have a proper client id, so it probably won't fail.
Although, its a login url as far as I can see, and I'd rather have proper sign out when my cookie expires.
In any case, my app uses multiple optional identity providers and relies on the backend to do full sign-out flow when session expires. So I don't follow the redirect, but rather identify this event as session expires.
So the client posts sign-out request
```
POST
https://localhost:5001/api/authentication/signout
Status Code: 302 Redirect
```
The response header includes a different redirect url then:
```
Location: https://apiiro.okta.com/oauth2/v1/logout?post_logout_redirect_uri=https%3A%2F%2Flocalhost%3A5001%2Fsignout%2Fcallback&state=xxx&x-client-SKU=xxx&x-client-ver=5.5.0.0
```
Then when following this url I get the above mentioned error.
```
GET https://apiiro.okta.com/oauth2/v1/logout?post_logout_redirect_uri=https%3A%2F%2Flocalhost%3A5001%2Fsignout%2Fcallback&state=xxx&x-client-SKU=xxx&x-client-ver=5.5.0.0
Status Code: 400 Bad Request
```
with body
```
{"errorCode":"invalid_client","errorSummary":"Invalid value for 'client_id' parameter.","errorLink":"invalid_client","errorId":"oaeo2ADSYZaSLeb98IJa437DA","errorCauses":[]}
```

**Comment by laura-rodriguez** [comment]
Hi @liiri ,

Thanks for the additional details.

It seems your logout URL doesn't have an `id_token_hint` and I think that's the issue. I know the `client_id` error message can be misleading, but I have seen the same error message when the id_token wasn't properly passed during logout. Your logout URL should like this:

`GET /oauth2/default/v1/logout?post_logout_redirect_uri=https%3A%2F%2Flocalhost%3A44314%2Fsignout%2Fcallback&id_token_hint=eyJraWQiOiIzV0UwZEFoZzZzbDF1cnZ3LXVx........&x-client-SKU=ID_NETSTANDARD2_0&x-client-ver=5.5.0.0 HTTP/1.1`

(id_token has been edited and I haven't configured a `post_logout_redirect_uri` that's why it's not there )

You mentioned that if you log out before your session expires, everything is working as expected. Would you mind sharing the logout URL when logging out before your session expires? I want to verify that in that case the `id_token_hint` is correctly passed.

Thank you!

**Comment by liiri** [comment]
Nevermind, it was my misunderstanding, on manual flow we got the same problem, its just that when clicking the "log out" button, my app also manually redirects to sign-in page, which overrides the behavior.

In any case, the URL is built using the sdk and I don't see any config option where I can pass `id_token_hint`

**Comment by laura-rodriguez** [comment]
That's fine. You don't have to configure the `id_token`, the SDK internally builds the logout URL passing all the required params, including the `id_token_hint`.

So, it seems you figured it out and we can close this issue. Feel free to reopen if that's not the case. Thanks!
