### ISSUE TITLE
Refresh Session

### ISSUE THREAD

**Issue by om2468** [okta/okta-aspnet#171]
In Postman I am trying to test the Refresh Session

https://developer.okta.com/docs/reference/api/sessions/
I am taking the session token from the ASP.NET_SessionId - is this the correctID to use in the following API call?

/api/v1/sessions/${sessionId}/lifecycle/refresh

If not how to I obtain the current sessionId, thank you.

Do I need to take anything from the returned call to keep the session active or can I continue to use this SessionId. I.e. with a session refresh do you keep the same sessionid or does it change?

Thanks

**Comment by bryanapellanes-okta** [comment]
@om2468,
Thanks for reaching out!  Based on the documentation, you should be able to use the ASP.NET_SessionId if it is the same value you used when the session token was created (https://developer.okta.com/docs/reference/api/sessions/#create-session-with-a-session-token):

Below is an excerpt from documentation for the `POST /api/v1/sessions` endpoint:

_Use this API if, for example, you want to set the session cookie yourself instead of allowing Okta to set it, or you want to hold the Session ID to delete a Session through the API instead of visiting the logout URL._

I hope this helps.  

Thanks for using Okta!
