### ISSUE TITLE
Would it be possible to get a working sample with the latest versions of your dll and identitymodel 4?

### ISSUE THREAD

**Issue by StephaneCT** [okta/okta-aspnet#98]
Would it be possible to get a working sample with the latest versions of your dll and identitymodel 4?
okta-hosted-login is the one i’d like
Identity Model 4.0 and Okta Asp.Net 1.4.0

Thanks
–steph

**Comment by laura-rodriguez** [comment]
Hi @StephaneCT,

So sorry for the late response! 
I need to discuss with the team the priority of this issue since we are working on other .NET projects at the moment. Anyways, I have a couple of questions:

* What .NET version are you using?
* What are the features of IdentityModel 4.0.0 that you want to use?
* Are you blocked?

**Comment by laura-rodriguez** [comment]
Consider re-open if this is still an issue.
